# Generated by Django 5.2.6 on 2025-09-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_add_booking_approval_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApproverAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this assignment is currently active",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this assignment was created"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this assignment"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        help_text="The resident designated to approve bookings for this common area",
                        limit_choices_to={"is_active": True, "user_type": "resident"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approver_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who assigned this approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approvers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "common_area",
                    models.ForeignKey(
                        help_text="The common area for which this resident is designated as approver",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approver_assignments",
                        to="backend.commonarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approver Assignment",
                "verbose_name_plural": "Approver Assignments",
                "ordering": ["common_area__name", "approver__first_name"],
                "unique_together": {("common_area", "approver")},
            },
        ),
    ]
