# Generated by Django 5.2.6 on 2025-09-21 06:05

from django.db import migrations


def create_initial_approver_assignments(apps, schema_editor):
    """
    Create initial approver assignments for existing common areas.
    
    This migration sets up the initial approver assignments based on the
    hardcoded logic that was previously in the Booking model:
    - Community Hall → sanjaysingh13
    - Garden → ajoykumar
    """
    ApproverAssignment = apps.get_model('backend', 'ApproverAssignment')
    CommonArea = apps.get_model('backend', 'CommonArea')
    User = apps.get_model('users', 'User')
    
    # Mapping of common area names to approver usernames
    approver_mapping = {
        'Community Hall': 'sanjaysingh13',
        'Garden': 'ajoykumar',
        'Garden Area': 'ajoykumar',  # Alternative name
        'Community Center': 'sanjaysingh13',  # Alternative name
    }
    
    # Create assignments for existing common areas
    for common_area in CommonArea.objects.all():
        approver_username = approver_mapping.get(common_area.name)
        
        if approver_username:
            try:
                # Find the approver user
                approver = User.objects.get(
                    username=approver_username,
                    user_type='resident',
                    is_active=True
                )
                
                # Create the assignment if it doesn't exist
                ApproverAssignment.objects.get_or_create(
                    common_area=common_area,
                    approver=approver,
                    defaults={
                        'is_active': True,
                        'notes': f'Initial assignment created by migration'
                    }
                )
                
            except User.DoesNotExist:
                # Log warning if approver not found
                print(f"Warning: Approver '{approver_username}' not found for common area '{common_area.name}'")


def reverse_approver_assignments(apps, schema_editor):
    """
    Reverse the initial approver assignments.
    """
    ApproverAssignment = apps.get_model('backend', 'ApproverAssignment')
    ApproverAssignment.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_approverassignment"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_approver_assignments,
            reverse_approver_assignments
        ),
    ]
