# Generated by Django 5.2.6 on 2025-09-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_populate_residents_from_csv"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="owner_email",
            field=models.EmailField(
                blank=True, help_text="Owner email from CSV data", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="owner_name",
            field=models.CharField(
                blank=True, help_text="Owner name from CSV data", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="flat_number",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="resident",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resident",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
