# Generated by Django 5.2.6 on 2025-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_add_owner_data_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="flat_number",
            field=models.CharField(max_length=10),
        ),
    ]
