# Generated by Django 5.2.6 on 2025-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_update_flat_number_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="block",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
