# Generated by Django 5.2.6 on 2025-09-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_update_block_field_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Photo to be shared in the gallery",
                        upload_to="gallery/",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, help_text="Optional caption for the photo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this photo is approved for public viewing",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this photo is featured in the gallery",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Resident who shared this photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Photo",
                "verbose_name_plural": "Gallery Photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Comment content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this comment is approved for public viewing",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment for threaded discussions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="backend.gallerycomment",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        help_text="Photo being commented on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="backend.galleryphoto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Comment",
                "verbose_name_plural": "Gallery Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who liked the photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        help_text="Photo that was liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="backend.galleryphoto",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("photo", "user")},
            },
        ),
    ]
