# Generated by Django 5.2.6 on 2025-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("resident", "Resident"), ("staff", "Staff")],
                default="resident",
                help_text="Type of user - resident or maintenance staff",
                max_length=10,
            ),
        ),
    ]
